package site

// hydrationFixUI mantiene las URLs del CDN pasando por el mirror e inyecta
// las acciones locales de refresco y descarga de serie.
const hydrationFixUI = `<script>(function(){
var CDN='https://cdn.animeav1.com/',scheduled=false;
function localizeValue(v){if(!v||v.indexOf(CDN)===-1)return v;return v.split(CDN).join('/_cdn/')}
function fixAttrs(root){var nodes=[];if(root&&root.nodeType===1)nodes.push(root);if(root&&root.querySelectorAll)nodes=nodes.concat(Array.prototype.slice.call(root.querySelectorAll('[src],[srcset],[poster],[data-src],[data-lazy-src]')));nodes.forEach(function(el){['src','srcset','poster','data-src','data-lazy-src'].forEach(function(a){var v=el.getAttribute&&el.getAttribute(a),n=localizeValue(v);if(v&&n!==v)el.setAttribute(a,n)})})}
function shareButton(){return Array.prototype.slice.call(document.querySelectorAll('button,a')).find(function(el){var t=(el.textContent||'').trim(),a=(el.getAttribute('aria-label')||'')+' '+(el.getAttribute('title')||'');return /compartir/i.test(t)||/compartir|share/i.test(a)})}
function iconButton(id,ref,title,svg){var b=document.createElement('button');b.id=id;b.type='button';b.className=ref.className;b.title=title;b.setAttribute('aria-label',title);b.innerHTML=svg;b.style.marginLeft='4px';return b}
function fmtBytes(n){if(!n)return '0 B';var u=['B','KB','MB','GB','TB'],i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return (i<2?Math.round(x):x.toFixed(1))+' '+u[i]}
function statusLabel(s){return {pending:'Pendiente',checking:'Buscando fuente',downloading:'Descargando',completed:'Completado',existing:'Ya existe',error:'Error'}[s]||s||'Pendiente'}
function ensureModal(){var old=document.getElementById('mirror-download-modal');if(old)return old;var wrap=document.createElement('div');wrap.id='mirror-download-modal';wrap.innerHTML='<div class="mirror-modal-card"><div class="mirror-modal-head"><div><div class="mirror-modal-title">Descargar serie</div><div id="mirror-dl-series" class="mirror-modal-sub"></div></div><button type="button" id="mirror-dl-close" class="mirror-modal-close" aria-label="Cerrar">×</button></div><div id="mirror-dl-summary" class="mirror-dl-summary"></div><div class="mirror-progress"><div id="mirror-dl-progress"></div></div><div id="mirror-dl-list" class="mirror-dl-list"></div><div id="mirror-dl-error" class="mirror-dl-error"></div><div class="mirror-modal-foot"><button type="button" id="mirror-dl-close2">Cerrar</button></div></div>';document.body.appendChild(wrap);function close(){wrap.classList.remove('open')}wrap.querySelector('#mirror-dl-close').onclick=close;wrap.querySelector('#mirror-dl-close2').onclick=close;wrap.addEventListener('click',function(e){if(e.target===wrap)close()});return wrap}
function renderModal(x,title){var m=ensureModal();m.classList.add('open');m.querySelector('#mirror-dl-series').textContent=title||x.slug||'';var total=x.total||0,done=(x.downloaded||0)+(x.skipped||0)+(x.errors||0),pct=total?Math.min(100,Math.round(done*100/total)):0;m.querySelector('#mirror-dl-summary').textContent=(x.running?'Descarga en curso':'Descarga finalizada')+' · '+done+' / '+total+' · '+(x.downloaded||0)+' descargados · '+(x.skipped||0)+' existentes · '+(x.errors||0)+' errores';m.querySelector('#mirror-dl-progress').style.width=pct+'%';var list=m.querySelector('#mirror-dl-list');list.innerHTML='';(x.episodes||[]).forEach(function(e){var row=document.createElement('div');row.className='mirror-dl-row '+(e.status||'pending');var left=document.createElement('div');left.innerHTML='<strong>Episodio '+e.episode+'</strong><span>'+statusLabel(e.status)+(e.provider?' · '+e.provider:'')+'</span>';var right=document.createElement('div');right.className='mirror-dl-right';if(e.status==='downloading'&&e.total_bytes){var p=Math.min(100,Math.round((e.bytes||0)*100/e.total_bytes));right.textContent=fmtBytes(e.bytes)+' / '+fmtBytes(e.total_bytes)+' · '+p+'%'}else if(e.file){right.textContent=e.file}else if(e.error){right.textContent=e.error}row.appendChild(left);row.appendChild(right);list.appendChild(row)});var er=m.querySelector('#mirror-dl-error');er.textContent=x.last_error?('Último error: '+x.last_error):''}
function ensureActions(){try{var match=location.pathname.match(/^\/media\/([^/]+)\/?$/);if(!match)return;var slug=match[1],share=shareButton();if(!share)return;
if(!document.getElementById('mirror-refresh-series')){var b=iconButton('mirror-refresh-series',share,'Actualizar esta ficha desde AnimeAV1','<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 11a8 8 0 0 0-15.5-2M4 4v5h5"/><path d="M4 13a8 8 0 0 0 15.5 2M20 20v-5h-5"/></svg>');b.addEventListener('click',async function(){if(b.disabled)return;b.disabled=true;b.classList.add('mirror-refreshing');try{var r=await fetch('/__mirror/refresh?path='+encodeURIComponent(location.pathname),{method:'POST',headers:{'X-Mirror-Action':'refresh-series'}});if(!r.ok)throw new Error(await r.text());location.reload()}catch(e){b.disabled=false;b.classList.remove('mirror-refreshing');alert('No se pudo actualizar la ficha: '+e.message)}});share.insertAdjacentElement('afterend',b)}
if(!document.getElementById('mirror-download-series')){var anchor=document.getElementById('mirror-refresh-series')||share,d=iconButton('mirror-download-series',share,'Descargar todos los episodios que falten','<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg>'),timer=null;function title(){var h=document.querySelector('h1');return h?(h.textContent||'').trim():slug}function apply(x,show){d.classList.toggle('mirror-downloading',!!x.running);d.title=x.running?'Descarga en curso · pulsa para ver progreso':'Descargar todos los episodios que falten';if(show)renderModal(x,title());if(timer)clearTimeout(timer);if(x.running)timer=setTimeout(function(){load(show)},1500)}function load(show){return fetch('/api/download-status?slug='+encodeURIComponent(slug),{cache:'no-store'}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(x){apply(x,show);return x}).catch(function(){d.classList.remove('mirror-downloading');return null})}d.addEventListener('click',async function(){var x=await load(false);if(x&&x.running){apply(x,true);return}if(x&&!x.running&&x.finished){apply(x,true);return}if(!confirm('Descargar al NAS todos los episodios que falten de esta serie?'))return;d.classList.add('mirror-downloading');try{var f=new URLSearchParams();f.set('slug',slug);var r=await fetch('/api/download-series',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:f.toString()});if(!r.ok)throw new Error(await r.text());x=await r.json();apply(x,true)}catch(e){d.classList.remove('mirror-downloading');alert('No se pudo iniciar la descarga: '+e.message)}});anchor.insertAdjacentElement('afterend',d);load(false)}
}catch(e){console.error(e)}}
function run(){scheduled=false;fixAttrs(document);ensureActions()}function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(run)}function start(){run();new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['src','srcset','poster','data-src','data-lazy-src']})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();</script><style>#mirror-refresh-series,#mirror-download-series{display:inline-flex;align-items:center;justify-content:center}.mirror-refreshing svg,.mirror-downloading svg{animation:mirror-spin .8s linear infinite}@keyframes mirror-spin{to{transform:rotate(360deg)}}#mirror-download-modal{position:fixed;inset:0;background:rgba(0,0,0,.72);z-index:99999;display:none;align-items:center;justify-content:center;padding:24px}#mirror-download-modal.open{display:flex}.mirror-modal-card{width:min(760px,96vw);max-height:86vh;overflow:hidden;background:#15161d;color:#e8e9ef;border:1px solid #2c2f3d;border-radius:14px;box-shadow:0 20px 60px rgba(0,0,0,.5);display:flex;flex-direction:column}.mirror-modal-head,.mirror-modal-foot{display:flex;align-items:center;justify-content:space-between;padding:16px 18px;border-bottom:1px solid #2c2f3d}.mirror-modal-foot{border-bottom:0;border-top:1px solid #2c2f3d;justify-content:flex-end}.mirror-modal-title{font-size:20px;font-weight:700}.mirror-modal-sub{color:#9da3b4;margin-top:3px}.mirror-modal-close{font-size:28px;background:transparent;border:0;color:#c8cad4;cursor:pointer}.mirror-dl-summary{padding:14px 18px 8px;color:#c9cbd3}.mirror-progress{height:8px;background:#252836;margin:0 18px 12px;border-radius:999px;overflow:hidden}.mirror-progress>div{height:100%;width:0;background:#2dd4bf;transition:width .25s}.mirror-dl-list{overflow:auto;padding:0 18px 10px}.mirror-dl-row{display:flex;justify-content:space-between;gap:18px;padding:10px 2px;border-bottom:1px solid #242733}.mirror-dl-row>div:first-child{display:flex;flex-direction:column;gap:3px}.mirror-dl-row span{font-size:13px;color:#9da3b4}.mirror-dl-row.completed strong,.mirror-dl-row.existing strong{color:#2dd4bf}.mirror-dl-row.error strong,.mirror-dl-error{color:#fb7185}.mirror-dl-right{max-width:52%;text-align:right;color:#c9cbd3;font-size:13px;overflow-wrap:anywhere}.mirror-dl-error{padding:0 18px 10px}.mirror-modal-foot button{padding:8px 16px;border-radius:8px;border:1px solid #3a3f52;background:#262a38;color:#fff;cursor:pointer}</style>`
